export const apilist = {
    login : {
        url:"/auth/login",
        auth:false,
        method:'POST'
    },
    forgot : {
        url:"/auth/forgot-password",
        auth:false,
        method:'POST'
    },
    verifyOtp : {
        url:"/auth/verify-otp",
        auth:false,
        method:'POST'
    },
    resetPassword : {
        url:"/auth/reset-password",
        auth:false,
        method:'POST'
    },
    // 
    getUser:{
        url:"/users",
        auth:true,
        method:'GET'
    },
    getUserList:{
        url:"/users",
        auth:true,
        method:'GET'
    },
    deleteUser:{
        url:"/users",
        auth:true,
        method:'DELETE'
    },
    createUser:{
        url:"/users",
        auth:true,
        method:'POST'
    },
    updateUser:{
        url:"/users",
        auth:true,
        method:'PUT'
    },
    // 
    // 
    getWarehouse:{
        url:"/warehouses",
        auth:true,
        method:'GET'
    },
    getWarehouseList:{
        url:"/warehouses",
        auth:true,
        method:'GET'
    },
    deleteWarehouse:{
        url:"/warehouses",
        auth:true,
        method:'DELETE'
    },
    createWarehouse:{
        url:"/warehouses",
        auth:true,
        method:'POST'
    },
    updateWarehouse:{
        url:"/warehouses",
        auth:true,
        method:'PUT'
    },
    // 
    // 
    getShippingVendor:{
        url:"/shipping-vendors",
        auth:true,
        method:'GET'
    },
    getShippingVendorList:{
        url:"/shipping-vendors",
        auth:true,
        method:'GET'
    },
    deleteShippingVendor:{
        url:"/shipping-vendors",
        auth:true,
        method:'DELETE'
    },
    createShippingVendor:{
        url:"/shipping-vendors",
        auth:true,
        method:'POST'
    },
    updateShippingVendor:{
        url:"/shipping-vendors",
        auth:true,
        method:'PUT'
    },
    // 
    
    getInventoriess:{
        url:"/inventoriess",
        auth:true,
        method:'GET'
    },
    getInventoryList:{
        url:"/inventories",
        auth:true,
        method:'GET'
    },
    getWarhouseList:{
        url:"/warehouses",
        auth:true,
        method:'GET'
    },
    // 

    // 
    getClient:{
        url:"/clients",
        auth:true,
        method:'GET'
    },
    getClientList:{
        url:"/clients",
        auth:true,
        method:'GET'
    },
    deleteClient:{
        url:"/clients",
        auth:true,
        method:'DELETE'
    },
    createClient:{
        url:"/clients",
        auth:true,
        method:'POST'
    },
    updateClient:{
        url:"/clients",
        auth:true,
        method:'PUT'
    },



    getProject:{
        url:"/projects",
        auth:true,
        method:'GET'
    },
    getProjectList:{
        url:"/projects",
        auth:true,
        method:'GET'
    },
    deleteProject:{
        url:"/projects",
        auth:true,
        method:'DELETE'
    },
    createProject:{
        url:"/projects",
        auth:true,
        method:'POST'
    },
    updateProject:{
        url:"/projects",
        auth:true,
        method:'PUT'
    },

    


    getPodeposit:{
        url:"/po-deposits",
        auth:true,
        method:'GET'
    },
    getPodepositList:{
        url:"/po-deposits",
        auth:true,
        method:'GET'
    },
    deletePodeposit:{
        url:"/po-deposits",
        auth:true,
        method:'DELETE'
    },
    createPodeposit:{
        url:"/po-deposits",
        auth:true,
        method:'POST'
    },
    updatePodeposit:{
        url:"/po-deposits",
        auth:true,
        method:'PUT'
    },


    projectDelivery:{
        url:"/projects/delivery",
        auth:true,
        method:'PUT'
    },
    getSnippet:{
        url:"/projects/snippet",
        auth:true,
        method:'GET'
    },
    // 
    getNotificationCount:{
        url:"/notifications/unread-count",
        auth:true,
        method:'GET'
    },
    getNotificationList:{
        url:"/notifications",
        auth:true,
        method:'GET'
    },
    readNotification:{
        url:"/notifications/set-read",
        auth:true,
        method:'POST'
    },
    setToken:{
        url:"/notifications/set-token",
        auth:true,
        method:'POST'
    },
    // 
    getDeliveryList:{
        url:"/deliveries/list",
        auth:true,
        method:'GET'
    },
    createDelivery:{
        url:"/deliveries",
        auth:true,
        method:'POST'
    },
    updateDelivery:{
        url:"/deliveries",
        auth:true,
        method:'PUT'
    },
    deleteDelivery:{
        url:"/deliveries",
        auth:true,
        method:'DELETE'
    },
    getDelivery:{
        url:"/deliveries",
        auth:true,
        method:'GET'
    },
    getLogsList:{
        url:"/deliveries/logss",
        auth:true,
        method:'GET'
    },
    getLogList:{
        url:"/deliveries/logs",
        auth:true,
        method:'GET'
    },
    getLog:{
        url:"/deliveries/log",
        auth:true,
        method:'GET'
    },
    getMisc:{
        url:"/deliveries/misc",
        auth:true,
        method:'GET'
    },
    // 
    
    createProgress:{
        url:"/invoice-progress",
        auth:true,
        method:'POST'
    },
    getProgress:{
        url:"/invoice-progress",
        auth:true,
        method:'GET'
    },
    // 
    createThreads:{
        url:"/threads",
        auth:true,
        method:'POST'
    },
    getThreads:{
        url:"/threads",
        auth:true,
        method:'GET'
    },
    getThreadsCount:{
        url:"/threads",
        auth:true,
        method:'GET'
    },
    // 
    
    createFollowup:{
        url:"/marketing-followup",
        auth:true,
        method:'POST'
    },
    updateFollowup:{
        url:"/marketing-followup",
        auth:true,
        method:'PUT'
    },
    getFollowup:{
        url:"/marketing-followup",
        auth:true,
        method:'GET'
    },
    getReport:{
        url:"/report",
        auth:true,
        method:'GET'
    },

    upload:{
        url:"/upload",
        auth:true,
        method:'POST'
    }

}